version: "3.8"

services:
  front:
    #    image: pfc:latest
    build:
      context: .
      dockerfile: ./Dockerfile-front
    ports:
      - "8080:80"
    networks:
      - pfcnet
    links:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile-server
    #    image: pfc_backend:latest
    ports:
      - "18080:80"
    volumes:
      - ./server/config/config.js:/config/config.js
    networks:
      - pfcnet
    links:
      - db

  db:
    image: library/mongo:3-xenial
    restart: on-failure:3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: dbchifoumi
    volumes:
      - pfcdata:/data/db
    networks:
      - pfcnet


networks:
  pfcnet:
volumes:
  pfcdata:
